build.gradle
This should fix IntelliJ IDEA not being able to run Spek tests.
See: [https://github.com/raniejade/spek-idea-plugin#requirements](https://github.com/raniejade/spek-idea-plugin#requirements)
Fixes #27
=> Fixes idea not able to run spek tests

README.md
Correcting the README to show that you need to  use `it.hasMessage(String)` 
If you do not then the IDE will continuously attempt to automatically add the following import
`import org.junit.internal.matchers.ThrowableMessageMatcher.hasMessage` which may confuse some people
=> Add `it` in docs to ensure correct package usage

src/main/kotlin/assertk/assert.kt, src/main/kotlin/assertk/assertions/any.kt, src/main/kotlin/assertk/assertions/support/support.kt, src/test/kotlin/test/assertk/assertions/ThrowableSpec.kt
Also make the prop internal so it's not part of the public api.
It's a bit simpiler to implement.
=> Pass context instead of parent assertion.

CHANGELOG.md, src/main/kotlin/assertk/assertions/string.kt, src/test/java/test/assertk/assertions/JavaNullableString.java, src/test/kotlin/test/assertk/assertions/StringSpec.kt
=> Fixed issue where you couldn't select `isEqualTo` for nullable java strings

src/main/kotlin/assertk/assert.kt
Previously, the following code is possible:
```kotlin
assert("hello").all {
isInstanceOf(String::class)
toStringFun().isEqualTo("hello")
prop(String::length).all {
length().isEqualTo(5)
isGreaterThan(4)
}
}
```
This could lead to confusing code of "which block am I making the assertion on?"
With the addition of `@DslMarker`, that code will generate a compiler error like:
> 'fun <T : CharSequence> Assert<String>.length(): Assert<Int>' can't be called in this context by implicit receiver. Use the explicit one if necessary
If users want to continue doing this, they will need to be explicit with the receiver.
```kotlin
assert("hello").all string@ {
isInstanceOf(String::class)
toStringFun().isEqualTo("hello")
prop(String::length).all {
this@string.length().isEqualTo(5)
isGreaterThan(4)
}
}
``` …
=> Use `@DslMarker` to delimit assertion DSL to prevent confusing code

src/main/kotlin/assertk/assertions/collection.kt, src/test/kotlin/test/assertk/assertions/CollectionSpec.kt
Fixes #5 by adding additional info to the expectation messages about items that are missing/superfluous/different for the following collection asserts:
- containsAll
- containsNone
- containsExactly
added some tests to cover corner cases for the new implementation of containsExactly
=> Error messages could be better for collections with lots of items

src/main/kotlin/assertk/assertions/any.kt, src/test/kotlin/test/assertk/assertions/AnyTest.kt
Add `isEqualToComparingOnlyGivenProperties` to make comparisons on given properties of an object. 
This aims to be a typesafe version of assertj's [`isEqualToComparingOnlyGivenFields`](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#field-by-field-only)
=> Add assertion to compare only given properties

CHANGELOG.md, src/main/kotlin/assertk/assertions/any.kt, src/main/kotlin/assertk/assertions/list.kt, src/main/kotlin/assertk/assertions/map.kt, src/test/kotlin/test/assertk/LensAssertSpec.kt
This is to have better error messages when the collection does not have the
given entry. It also better matches `isNotNull {}`.
=> Update index and key to take a lambda

assertk-common/build.gradle, assertk-common/src/main/kotlin/assertk/assertions/support/support.kt, assertk-common/src/template/assertk/assertions/primativeArray.kt, assertk-common/src/testTemplate/test/assertk/assertions/PrimativeArrayTest.kt, assertk-js/src/main/kotlin/assertk/assertions/support/support.kt, assertk-js/src/main/kotlin/assertk/failure.kt, assertk-jvm/src/main/kotlin/assertk/assertions/support/support.kt, assertk-jvm/src/main/kotlin/assertk/failure.kt, buildSrc/build.gradle, buildSrc/src/main/kotlin/TemplateTask.kt
See buildSrc/src/main/kotlin/TemplateTask.kt for details.
Fixes #79
=> Support primative array types through simple templating system

assertk-jvm/build.gradle
We have test coverage of **62%** today. So I gave the minimal test coverage of **61%**. If any commit/PR `reduces the test coverage` the `pipeline will fail` which will help us in maintaining the good test coverage.
=> Add jacoco report creation and test coverage verification for test task

assertk-common/src/main/kotlin/assertk/assertions/map.kt, assertk-common/src/test/kotlin/test/assertk/assertions/MapTest.kt
This pull request changes the assertion message of `Assert<Map<K,V>>.containsAll()` to display actual map and expected map of elements. Currently it displays expected map and pair of elements that were not found.
This is in response to [https://github.com/willowtreeapps/assertk/issues/150](url)
=> Change assertion message for containsAll on Map

assertk-common/src/main/kotlin/assertk/assertions/array.kt, assertk-common/src/test/kotlin/test/assertk/assertions/ArrayTest.kt
This pull request changes the assertion message of Assert<Array<T>>.containsAll() to display actual array, expected array and missing elements.
=> Change assertion message for containsAll on Array

assertk-common/src/main/kotlin/assertk/assert.kt, assertk-common/src/main/kotlin/assertk/assertions/iterable.kt, assertk-common/src/main/kotlin/assertk/assertions/predicate.kt, assertk-common/src/main/kotlin/assertk/failure.kt, assertk-common/src/test/kotlin/test/assertk/assertions/IterableTest.kt, assertk-common/src/test/kotlin/test/assertk/assertions/PredicateTest.kt
Added variant of `all` that takes a predicate to choose if there is a
failure or not based on failures in the body. `atLeast` uses this to
fail if at least `times` items do not pass.
Renamed `assertPredicate` to `matchesPredicate`.
=>  Add support for conditional failures. 

assertk-common/src/main/kotlin/assertk/assertions/iterable.kt, assertk-common/src/test/kotlin/test/assertk/assertions/AnyTest.kt, assertk-common/src/test/kotlin/test/assertk/assertions/IterableTest.kt
I've added two of the quantitative predicate assertions mentioned in #98 along with some tests. They're based on the existing `atLeast` assertion.
=> Add quantitative predicate assertions for atMost and exactly

CHANGELOG.md, assertk-common/src/main/kotlin/assertk/assertions/support/support.kt, assertk-common/src/main/kotlin/assertk/failure.kt, assertk-common/src/test/kotlin/test/assertk/FailureTest.kt, assertk-common/src/test/kotlin/test/assertk/assertions/support/SupportTest.kt, build.gradle
This makes sure that intellij (and possibly others) don't show an
actual/expected diff when actual and expected values aren't provided.
Fixes #180
=> Ensure correct AssertionFailedError constructor is called

assertk-common/src/main/kotlin/assertk/assertions/iterable.kt, assertk-common/src/test/kotlin/test/assertk/assertions/IterableTest.kt
I've added a none assertion for iterables and some tests. The behaviour should be the same as `noneMatch` in AssertJ.
=> Add none assertion for iterables

build.gradle, src/commonMain/kotlin/assertk/assert.kt, src/commonMain/kotlin/assertk/failure.kt, src/commonMain/kotlin/assertk/table.kt, src/commonTest/kotlin/test/assertk/AssertBlockTest.kt, src/jsTest/kotlin/test/assertk/JSAssertBlockTest.kt, src/jvmTest/kotlin/test/assertk/JVMAssertBlockTest.kt, src/nativeTest/kotlin/test/assertk/NativeAssertBlockTest.kt
Alternative to #201, making the existing `assertThat {}` inline so that it can work with existing coroutine testing functionally. While harder to write tests for multiplatform code, it should be more robust and side-steps the issues with the other solution. Hopefully the official tools for testing coroutines will improve (they are marked experimental now anyway).
=> Assert that inline

src/commonMain/kotlin/assertk/assertions/support/support.kt, src/commonTest/kotlin/test/assertk/assertions/support/SupportTest.kt
Like lists and maps, it'll display the contentens inside to make your
types more clear, so for `"one" to '2'` you'll now get `("one", '2')`
isntead of `(one, 2)`.
=> Better display of pairs and triples

CHANGELOG.md, src/commonMain/kotlin/assertk/assert.kt
=> Deprected catch in favor of assertThat {}.isFailure()

build.gradle, src/commonMain/kotlin/assertk/assertions/any.kt, src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
Sometimes you want to compare objects that don't have a proper equals
implementation. This makes it simpler to implement this. Ex:
```kotlin
fun Assert<CharSequence>.isEqualTo(other: CharSequence) {
isEqualTo(other) { a, b -> a.toString() == b.toString() }
}
```
=> Add optional equivalent function for isEqualTo/isNotEqualTo

src/commonMain/kotlin/assertk/assertions/any.kt, src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt, src/commonTest/kotlin/test/assertk/assertions/NumberTest.kt
You may think this wouldn't make a difference since T is covariant so
you can pass any anything as they share the same super-type `Any?`.
However, there _is_ a case where this is different and it has do with
kotliln's type inference on literal numbers.
If you have a literal number like `1` in the source code, kotlin will
try to infer it's type (byte, short, int, long) based on where it's
used. Ex: `val b: Byte = 1`. If it can't infer, it'll default to int.
By changing to use a generic type param instead of `Any?` for the
expected value, kotlin will now be able to infer the type.
Before this change:
```kotlin
assertThat(1L).isEqualTo(1)
```
would fail with `expected:<1[]> but was:<1[L]>`.
After this change:
```kotlin
assertThat(1L).isEqualTo(1)
```
passes.
I think this is worth doing …
=> Change the signature of `isEqualTo` from Any? to T

src/commonMain/kotlin/assertk/assert.kt, src/commonMain/kotlin/assertk/failure.kt, src/commonMain/kotlin/assertk/table.kt, src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt, src/jsMain/kotlin/assertk/failure.kt, src/jvmMain/kotlin/assertk/failure.kt, src/nativeMain/kotlin/assertk/failure.kt
Before pushing a soft failure when there was none would be ignored. This
causes a problem when using the failIf feature as that condition will be
ignored too.
Fixes #253
=> Use a proper stack for soft failures so they compose correctly

README.md
=> Fix spelling of "success"

CHANGELOG.md, src/commonMain/kotlin/assertk/assertions/string.kt, src/commonTest/kotlin/test/assertk/assertions/StringTest.kt
hi, i am missing a few assertions in assertk, which for the time being reside in some privately hosted repository. i'd like to start sharing those with the community, as i think they are essential and should reside in the core project itself (rather get dusty in some private shared library).
sorry i haven't opened up an issue upfront to discuss this. i hope/guess it's simple enough to just go for it ;)
PS: this pull request was created due to the FOSDEM 2020 kotlin open source initiative (https://fosdem.org/2020/schedule/track/kotlin/).
=> Add multi-value support for String contains assertion

assertk/src/commonTest/kotlin/test/assertk/AssertAllTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/ArrayTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt, assertk/src/jvmMain/kotlin/assertk/assertions/file.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/FileTest.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/JVMResultTest.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt, assertk/src/testTemplate/test/assertk/assertions/PrimativeArrayTest.kt
Fixes tests to work on Windows, and be generally more system-independent:
- Use `File.separator` to be separator-agnostic
- Compare error messages using `lines()` to be line separator-agnostic
One change to the actual library behavior: `assert(file).hasPath(path)` originally would fail on Windows to consider that a file `File("assertKt/file.txt")` has a path `"assertKt/file.txt"` because the `/` is replaced with a `\`. So that the tests using assertk are also system-independent, the `hasPath` method is revised to compare the file to a file that also has the expected path.
=> Make tests system-independent

assertk-coroutines/build.gradle, assertk-coroutines/src/commonMain/kotlin/assertk/coroutines/assertions/any.kt, assertk-coroutines/src/commonMain/kotlin/assertk/coroutines/assertions/flow.kt, assertk-coroutines/src/commonTest/kotlin/test/assertk/coroutines/assertions/AnyTest.kt, assertk-coroutines/src/commonTest/kotlin/test/assertk/coroutines/assertions/FlowTest.kt, assertk-coroutines/src/commonTest/kotlin/test/runTest.kt, assertk-coroutines/src/jsTest/kotlin/test/runTest.kt, assertk-coroutines/src/jvmTest/kotlin/test/runTest.kt, assertk-coroutines/src/nativeTest/kotlin/test/runTest.kt, assertk/src/commonMain/kotlin/assertk/assert.kt, assertk/src/commonMain/kotlin/assertk/assertions/any.kt, assertk/src/commonMain/kotlin/assertk/assertions/array.kt, assertk/src/commonMain/kotlin/assertk/assertions/iterable.kt, assertk/src/commonMain/kotlin/assertk/assertions/list.kt, assertk/src/commonMain/kotlin/assertk/assertions/map.kt, assertk/src/commonMain/kotlin/assertk/assertions/support/support.kt, assertk/src/jvmMain/kotlin/assertk/assertions/any.kt, assertk/src/template/assertk/assertions/primativeArray.kt, settings.gradle
Some implementation decisions:
- Created a new artifact: `assertk-coroutines`
- The new flow assertions are all `suspend`. This allows you to use them on all supported platforms. In java, you are likely to be wrapping your coroutine tests in a `runBlockingTest`, this plays nicely with that.
- `transform` has been made inline. This allows you to call suspend functions inside of it.
- Unstable coroutine api's are avoided for the most part. Except for cases where it's wrapping an unstable method: `count()`.
- Care is taken to support flows that don't complete when it makes sense.
=> Started on addding coroutine assertions, particuarly flow

assertk-coroutines/build.gradle, assertk/build.gradle, build.gradle, multiplatform.gradle
Not super happy about the random split between `multiplatform.gradle` and the top-level `build.gradle` but couldn't figure out another way to do it.
=> Clean up gradle scripts to share code

.circleci/config.yml
Identical jvmargs are already defined in gradle.properties.
CircleCI is upset:
```
* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.2/userguide/gradle_daemon.html
Process command line: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Xmx2048morg.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/distiller/.gradle/wrapper/dists/gradle-6.2-bin/6zaomcc3lf3gnwxgkllci1muk/gradle-6.2/lib/gradle-launcher-6.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.2
Please read the following process output to …
```
=> Removes ci step modifying gradle.properties with extra jvmargs.

assertk/src/commonMain/kotlin/assertk/assertions/charsequence.kt, assertk/src/commonMain/kotlin/assertk/assertions/string.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/CharSequenceTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/StringTest.kt
Most of the diff is a simple cut-paste from `strings.kt` and `StringTest.kt` to `charsequence.kt` and `CharSequence.kt`.
Slight modifications were required for `isEqualTo` and `isNotEqualTo`, as they both relied on the `String?` extension of `.equals` in the standard lib.
Also adds two tests that caught a bug I introduced with this change, specifically when comparing `null` to `"null"`
Couple thoughts:
1. Is there anything I'm missing that might cause a maintenance headache with this change?
2. Are there cases where this will break compilation for consumers?
=> Convert Assert<String> extensions into Assert<CharSequence> extensions.

assertk/src/commonMain/kotlin/assertk/failure.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt
In a nested context this was causing failures to be dropped since it was
mapping to an empty list.
Fixes #314
=> Don't throw MultipleFailuresError if failure list is empty

README.md, assertk-coroutines/README.md, assertk/README.md, assertk/build.gradle, build.gradle
Use the multimodule feature to publish the coroutines docs as well.
TODO: need to actually link to them from the README
=> Update dokka to 1.4.0

README.md
As a result of discussion in #365, added some documentation for the `contains*` assertions so that new users are able to pick the appropriate assertion and have a future reference to do so.
=> Document contains* assertions in README.md

assertk/src/commonMain/kotlin/assertk/assertions/list.kt
Fix an apparent copy-paste error which used containsOnly instead of containsExactly, which is a bit confusing.
=> Fix typo in documentation for containsExactly()

.circleci/config.yml
Following this (closed) PR, I realized that the CircleCI configuration needs to be updated:
https://github.com/willowtreeapps/assertk/pull/426
See https://app.circleci.com/pipelines/github/willowtreeapps/assertk/523/workflows/d454905d-6734-4e06-97a8-420604843aa8/jobs/1075
=> Updated MacOS version

README.md
The name of the parameter to `appendName` is `separator`.
=> Fix `seperator` typo in example

assertk/src/commonMain/kotlin/assertk/assert.kt, assertk/src/commonMain/kotlin/assertk/assertions/iterable.kt, assertk/src/commonMain/kotlin/assertk/collection.kt, assertk/src/commonMain/kotlin/assertk/failure.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt
to properly handle multiple assertions in the block. Also improves the failure message for none to include which passed.
=> Re-implement collection assertions: none,atLeast,atMost,exactly,any

CHANGELOG.md, assertk/src/template/assertk/assertions/primativeArray.kt, assertk/src/template/assertk/assertions/primativeArrayContains.kt, assertk/src/testTemplate/test/assertk/assertions/PrimativeArrayContainsTest.kt, assertk/src/testTemplate/test/assertk/assertions/PrimativeArrayTest.kt, buildSrc/src/main/kotlin/TemplateTask.kt
These are still experimental and so an annotation propagating that is added to the codegen for these types only.
I've modified the `TemplateTask` to support multiline declarations. I did it in a separate commit since it's technically orthogonal to the unsigned change.
=> Add unsigned arrays to array template

buildSrc/src/main/kotlin/assertk.publish.gradle.kts
This works around a Kotlin multiplatform publishing bug.
See https://youtrack.jetbrains.com/issue/KT-46466
Refs #443
=> Add implicit task dependency workaround

buildSrc/build.gradle.kts
Otherwise the running JDK version is used, which is sometimes unsupported (e.g., today with JDK 20).
This is copied from the convention plugin which applies to the normal modules, but it also needs to happen in the `buildSrc` which is a separate Gradle build.
Today, with JDK 20, you get:
```
> Task :buildSrc:compileKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':buildSrc:compileKotlin'.
> Failed to calculate the value of property 'jvmTarget'.
> Unknown Kotlin JVM target: 20
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
...
Caused by: java.lang.IllegalArgumentException: Unknown …
```
=> Set the Java and Kotlin bytecode targets

assertk/src/jvmTest/kotlin/test/assertk/JVMAssertLambdaTest.kt
Any non-zero value will trigger suspension. Let's do 10 milliseconds instead of 10 seconds to save 20 seconds from wall clock time.
=> Make tests 20s faster

assertk/src/commonMain/kotlin/assertk/assertions/any.kt
`S` is only used to limit the receiver which means we can replace it with its bound (`Any`) and let the `out` variance support any subtype (such as `Assert<String>`) remain valid.
As far as I can tell this second generic was introduced as part of b817dc3c8b7915b3bbb147a4d82144dd377a478a, where `S` is actually used to hold an instance. But when the lambda was eventually removed the extra generic stuck around until today.
=> Simplify generics of `isInstanceOf`

assertk/src/commonMain/kotlin/assertk/assertions/support/support.kt, assertk/src/commonMain/kotlin/assertk/failure.kt, assertk/src/commonTest/kotlin/test/assertk/FailureTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/support/SupportTest.kt
This ensures that the full stacktrace can be seen to help identify the underlying source of a mismatch.
Consider the following two tests:
```kotlin
@Test fun demo1() {
assertThat { someFunction() }
.isFailure()
.isInstanceOf(IllegalStateException::class)
}
@Test fun demo2() {
assertThat { someFunction() }
.isFailure()
.hasMessage("failure!")
}
fun someFunction() {
deepFunction()
}
fun deepFunction() {
throw AssertionError("oh no!!!!!")
}
```
Demo 1's failure before:
org.opentest4j.AssertionFailedError: expected to be instance of:<class java.lang.IllegalStateException> but had class:<class java.lang.AssertionError> (Failure(java.lang.AssertionError: oh no!!!!!))
at app//test.assertk.FailureTest.demo1(FailureTest.kt:56)
... 43 more
Demo 1's failure after: …
=> Attempt to propagate a source throwable as a cause

assertk/src/commonMain/kotlin/assertk/assertions/charsequence.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/CharSequenceTest.kt
Unlike 'contains' this is a regex rather than a literal. Unlike 'matches' this looks for a subset of the charsequence to match rather than the entire contents.
Closes #452
=> Add 'containsMatch' assertion for CharSequence

assertk/src/commonMain/kotlin/assertk/assert.kt, assertk/src/commonTest/kotlin/test/assertk/AssertFailureTest.kt
This accepts a lambda which is expected to throw an exception which is wrapped into an `Assert<Throwable>`. Successful completion of the lambda block will result in a failure exception.
Closes #453. Pairs well with #460.
=> Add `assertFailure` entrypoint

CHANGELOG.md, README.md, assertk/src/commonMain/kotlin/assertk/assert.kt, assertk/src/commonMain/kotlin/assertk/assertions/result.kt
Use `assertFailure` for always-failing things and `assertThat(value)` for always-successful or `Result`-returning things.
Closes #464
=> Remove lambda-accepting `assertThat` overload

assertk/src/commonMain/kotlin/assertk/assert.kt
=> Use `try`/`catch` instead of `runCatching` for capturing exceptions

buildSrc/src/main/kotlin/TemplateTask.kt
The project had been failing to build on my Windows PC with the following rather cryptic exception:
Caused by: java.lang.StringIndexOutOfBoundsException: begin 324, end -1, length 5122
I tracked this down to use of hard-coded Unix-style line separator "\n" in TemplateTask.kt. Using the system's line separator corrected the problem.
I don't think this is likely to have any impact on non-Windows builds, as these templates are evidently dependent on the build platform, but releases already work on Windows, and clearly the build infrastructure is not Windows.
=> Fix the build on Windows

.circleci/config.yml
Following up from my previous PR, [Fix the build on Windows](https://github.com/willowtreeapps/assertk/pull/482), I had offered to adjust the CI to build the project on a Windows executor, and I took the suggestion from @evant to just add a Windows executor, and leave the binary publishing alone.
=> Add Windows build to CircleCI

assertk/src/commonMain/kotlin/assertk/assertions/any.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
This makes it more clear these functions are about instance identity see: https://truth.dev/comparison
#495
=> Rename isSameAs/isNotSameAs to isSameInstanceAs/isNotSameInstanceAs

assertk-coroutines/src/commonMain/kotlin/assertk/coroutines/assertions/flow.kt, assertk-coroutines/src/commonTest/kotlin/test/assertk/coroutines/assertions/FlowTest.kt, assertk/src/commonMain/kotlin/assertk/assertions/array.kt, assertk/src/commonMain/kotlin/assertk/assertions/iterable.kt, assertk/src/commonMain/kotlin/assertk/assertions/list.kt, assertk/src/commonMain/kotlin/assertk/assertions/map.kt, assertk/src/commonMain/kotlin/assertk/assertions/sequence.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/ArrayTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/MapTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/SequenceTest.kt, assertk/src/template/assertk/assertions/floatArrayContains.kt, assertk/src/template/assertk/assertions/primativeArrayContains.kt, assertk/src/testTemplate/test/assertk/assertions/FloatArrayContainsTest.kt, assertk/src/testTemplate/test/assertk/assertions/PrimativeArrayContainsTest.kt
This makes it more clear that the collection can contain additional elements
see: https://truth.dev/comparison
#495
=> Rename containsAll to containsAtLeast

CHANGELOG.md, assertk/src/commonMain/kotlin/assertk/assertions/map.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/MapTest.kt
Just adding a convenience assertion `Map::doesNotContainKey`. While existing assertions on `Map` can achieve the same functionality, having to pass an arbitrary value in addition to the key to be checked is overhead this PR endeavors to eliminate.
=> add map assertion doesNotContainKey

assertk/src/commonMain/kotlin/assertk/assertions/support/support.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
if the types are different, add them to the error message, otherwise just print out that they don't compare equal
Fixes #449
=> print disambiguation message if display is the same

assertk/src/commonMain/kotlin/assertk/failure.kt, assertk/src/commonTest/kotlin/test/assertk/AssertAllTest.kt, assertk/src/jsMain/kotlin/assertk/failure.kt, assertk/src/jvmMain/kotlin/assertk/failure.kt, assertk/src/jvmTest/kotlin/test/assertk/JVMAssertAllTest.kt, assertk/src/nativeMain/kotlin/assertk/failure.kt, assertk/src/nativeTest/kotlin/test/assertk/NativeAssertAllTest.kt, assertk/src/wasmJsMain/kotlin/assertk/failure.kt
If you had
```kotlin
assertAll {
assertThat(1).isEqualTo(2)
throw IllegalStateException("Broken!")
}
```
the `IllegalStateException` would be swallowed. It'll now be the primary exception you see. This more closely matches the mental model where soft assertions are thrown at the end of the block.
For convenience the assertion failure is added as a suppressed exception. Kotlin has mixed support for this (jvm shows the suppressed exception trace and error message, native just shows the trace, and js doesn't show it at all). This is acceptable as the inline exception is likely the one you care about fixing anyway.
Fixes #475
=> prioritize exceptions thrown directly in soft assertion blocks

assertk/src/jvmMain/kotlin/assertk/assertions/file.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/FileTest.kt
I know we're all waiting for #448 or #450 to utilize the existing (heh) `exists()` with some kind of negation, but I run into this missing assertion so much that I think it's probably safe enough to add for now.
=> Add File `doesNotExist` assertion

.circleci/config.yml
Modify the resource on mac os according to [this](https://github.com/willowtreeapps/assertk/pull/542#pullrequestreview-2166894935) comment.
However, I've never used the Circle CI, so it might be the wrong fix. If that's the case, feel free to close this PR.
=> Update CI to m1 resource

CHANGELOG.md, assertk/src/jvmMain/kotlin/assertk/assertions/path.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/PathTest.kt
`Assert<Path>.exists()` exists, but its negation, `Assert<Path>.doesNotExist()`, does not. Add `doesNotExist()` to Path for clean negation assertions.
=> Add Path `doesNotExist` assertion

assertk-coroutines/README.md
The `testCompile` configuration has been deprecated for dependency declaration.
=> Use testImplementation instead of testCompile

CHANGELOG.md, assertk/src/commonMain/kotlin/assertk/assertions/any.kt, assertk/src/commonMain/kotlin/assertk/assertions/boolean.kt, assertk/src/commonTest/kotlin/test/assertk/TableTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/BooleanTest.kt, assertk/src/jvmMain/kotlin/assertk/assertions/any.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt
This behavior brings it more line with how 'is' behaves in the language.
Refs #393. Refs #550.
=> Widen `isInstanceOf` assert to operate on nullable types

CHANGELOG.md, assertk/src/commonMain/kotlin/assertk/assertions/any.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
This adds some convenient methods when asserting something is (and is not) in something else. Previously due to `isIn` and `isNotIn` only accepting `vararg values: T`, this caused a somewhat confusing error.
Before:
```kotlin
@Test
fun demo() {
val possibleValues = listOf("test")
assertThat("test").isIn(possibleValues) // expected:<[["test"]]> to contain:<"test">
}
```
As mentioned in #549 to achieve something similar to above, you would need to spread an `Array<T>`
```kotlin
@Test
fun demo() {
val possibleValues = arrayOf("test")
assertThat("test").isIn(*possibleValues) // does not error
}
```
Now with `isIn(Iterable<T>)` and `isNotIn(Iterable<T>)`
```kotlin
@Test
fun demo() {
val possibleValues = listOf("test")
assertThat("test").isIn(possibleValues) // does not error
}
```
does not …
=> Add `isIn(Iterable<T>)` and `isNotIn(Iterable<T>)`

CHANGELOG.md, assertk/src/commonMain/kotlin/assertk/assertions/any.kt, assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
=> Force `isIn` and `isNotIn` callers to specify at least two elements

assertk/src/jvmMain/kotlin/assertk/assertions/any.kt, assertk/src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt
This fixes #551 by going right to `isEqualTo` if the passed value is a `data object`.
=> Fix `isDataClassEqualTo` not working with `data object`s
