willowtreeapps/assertk

- Contributing.md
- build.gradle
- src/main/kotlin/assertk/assertions/array.kt
- src/main/kotlin/assertk/assertions/support/support.kt
- src/test/kotlin/test/assertk/assertions/ArraySpec.kt
- src/test/kotlin/test/assertk/assertions/CollectionSpec.kt
- src/test/kotlin/test/assertk/assertions/MapSpec.kt
- Added array tests
- Moved map tests into their own file
- normalized the display of collections in failure messages
- fixed bug with array containsExactly
> Updates to collection tests

- src/test/kotlin/test/assertk/assertions/MapSpec.kt
added tests for map assertions. (partially address #17)
> Added MapSpec

- build.gradle
This is the latest version as of October 2017
> Upgrades Kotlin to v.1.1.50

- README.md
They need to handle `assertAll` properly.
> Add note about custom assertions

- src/main/kotlin/assertk/assertions/array.kt
- src/test/kotlin/test/assertk/assertions/ArraySpec.kt
Depends on #42 to update generated docs
> Add tests for array assertion. Fix documentation

- assertk-common/src/main/kotlin/assertk/assertions/string.kt
- assertk-common/src/test/kotlin/test/assertk/assertions/StringSpec.kt
> Add doesNotContain assertion for Strings

- assertk-common/src/main/kotlin/assertk/assertions/any.kt
- assertk-common/src/test/kotlin/test/assertk/assertions/AnyTest.kt
- assertk-jvm/src/main/kotlin/assertk/assertions/any.kt
- assertk-jvm/src/test/kotlin/test/assertk/assertions/JavaAnyTest.kt
This allows additional assertions when the value is the asserted type.
> Add optional lambda to isInstanceOf

- CHANGELOG.md
- build.gradle
- publish.gradle
> Fixed packaging issues

- assertk-common/src/main/kotlin/assertk/failure.kt
- assertk-common/src/test/kotlin/test/assertk/AssertAllTest.kt
> Fixed failure context failing to get reset if exception is thrown

- assertk-common/src/test/kotlin/test/assertk/assertions/StringTest.kt
> Updates StringSpec -> StringTest

- assertk-common/src/main/kotlin/assertk/assertions/collection.kt
- assertk-common/src/test/kotlin/test/assertk/assertions/CollectionTest.kt
Asserts the collection contains only the expected elements
In response to issue #118
> Add function containsOnly for collections

- assertk-jvm/src/main/kotlin/assertk/assertions/path.kt
- assertk-jvm/src/test/kotlin/test/assertk/assertions/PathTest.kt
> Adds Assert<Path>.lines and .bytes

- assertk-common/src/main/kotlin/assertk/assertions/array.kt
- assertk-common/src/main/kotlin/assertk/assertions/list.kt
- assertk-common/src/template/assertk/assertions/primativeArray.kt
- assertk-common/src/test/kotlin/test/assertk/assertions/ArrayTest.kt
- assertk-common/src/test/kotlin/test/assertk/assertions/ListTest.kt
- assertk-common/src/testTemplate/test/assertk/assertions/PrimativeArrayTest.kt
> containsExactly is now sorted by index

- assertk-common/src/test/kotlin/test/assertk/assertions/AnyTest.kt
I've added some tests to these methods since I couldn't find any in the project.
> Add tests for hasHashCode and hasToString

- assertk-common/src/main/kotlin/assertk/assertions/support/ListDiffer.kt
- assertk-common/src/test/kotlin/test/assertk/assertions/ListTest.kt
> Fix IndexOutOfBoundsException in containsExactly differ

- .circleci/config.yml
- build.gradle
- src/commonMain/kotlin/assertk/failure.kt
- src/commonMain/kotlin/assertk/platform.kt
- src/commonMain/kotlin/assertk/table.kt
- src/jvmMain/kotlin/assertk/failure.kt
- src/nativeMain/kotlin/assertk/assertions/support/support.kt
- src/nativeMain/kotlin/assertk/failure.kt
- src/nativeMain/kotlin/assertk/platform.kt
- src/nativeMain/kotlin/assertk/showError.kt
- src/nativeTest/kotlin/test/assertk/exceptionName.kt
Supports linux, macos, and ios targets.
> Add support for kotlin native

- src/commonMain/kotlin/assertk/failure.kt
- src/commonTest/kotlin/test/assertk/AssertAllTest.kt
- src/jsMain/kotlin/assertk/failure.kt
- src/jvmMain/kotlin/assertk/failure.kt
- src/jvmTest/kotlin/test/assertk/JVMAssertAllTest.kt
- src/nativeMain/kotlin/assertk/failure.kt
- src/nativeTest/kotlin/test/assertk/NativeAssertAllTest.kt
> Fix a thread-safety issue with soft assertions

- build.gradle
Also fixes a couple of extremely minor typos in the same metadata
> Fix site and scm URLs in generated POMs

- .circleci/config.yml
https://github.com/AdoptOpenJDK/openjdk-build/issues/1211
> Don't intstall java 11 on circleci macos

- src/commonMain/kotlin/assertk/assert.kt
- src/commonMain/kotlin/assertk/assertions/result.kt
- src/commonTest/kotlin/test/assertk/AssertLambdaTest.kt
- src/commonTest/kotlin/test/assertk/assertions/ResultTest.kt
> Fix isSuccess failing on null return values

- CHANGELOG.md
- src/commonMain/kotlin/assertk/assertions/any.kt
- src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
- src/jvmMain/kotlin/assertk/assertions/any.kt
- src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt
to be able to take nullable properties.
Fixes #247
> Changed `isEqualToWithGivenProperties` and `isEqualToIgnoringGivenProperties

- src/commonMain/kotlin/assertk/assertions/support/DiffExtractor.kt
- src/commonMain/kotlin/assertk/assertions/support/support.kt
- src/commonTest/kotlin/test/assertk/assertions/StringTest.kt
> Render tabs and newlines in diffs to make it clear why they are different

- src/commonMain/kotlin/assertk/assertions/iterable.kt
- src/commonMain/kotlin/assertk/table.kt
- src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt
This will pass if any item in the collection passes.
Fixes #252
> Add iterable assertion `any`

- src/commonMain/kotlin/assertk/assertions/list.kt
- src/commonTest/kotlin/test/assertk/assertions/ArrayTest.kt
- src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt
- src/commonTest/kotlin/test/assertk/assertions/ListTest.kt
- src/testTemplate/test/assertk/assertions/PrimativeArrayTest.kt
> Add full lists to the output of containsExactly

- .circleci/config.yml
- build.gradle
- gradle/ios-test.gradle
> Bump kotlin to 1.3.60

- src/commonMain/kotlin/assertk/assertions/array.kt
- src/commonMain/kotlin/assertk/assertions/collection.kt
- src/commonTest/kotlin/test/assertk/assertions/ArrayTest.kt
- src/commonTest/kotlin/test/assertk/assertions/CollectionTest.kt
- src/template/assertk/assertions/primativeArray.kt
- src/testTemplate/test/assertk/assertions/PrimativeArrayTest.kt
> Add containsOnly for arrays

- CHANGELOG.md
- assertk/src/commonMain/kotlin/assertk/assertions/any.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
- assertk/src/jvmMain/kotlin/assertk/assertions/any.kt
- assertk/src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt
> Deprecate prop with KCallable argument and add overload with KProperty1 argument

- README.md
- assertk-coroutines/README.md
- Add section on extracting data
- Expand section on custom assertions
> Doc improvements

- CHANGELOG.md
- assertk/src/commonMain/kotlin/assertk/assertions/list.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/ListTest.kt
> Fix containsExactly on a custom list type

- CHANGELOG.md
- assertk/src/jvmMain/kotlin/assertk/assertions/any.kt
- assertk/src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt
> Fixed npe in isDataClassEqualTo when a prop is null

- assertk/src/commonMain/kotlin/assertk/assertions/map.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/MapTest.kt
Follow up on https://github.com/willowtreeapps/assertk/issues/340
> Fixes some errors in assertions on maps

- CHANGELOG.md
- assertk/src/commonMain/kotlin/assertk/assert.kt
- assertk/src/commonMain/kotlin/assertk/assertions/iterable.kt
- assertk/src/commonMain/kotlin/assertk/failure.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt
> Handle multiple failures in any

- assertk/src/commonMain/kotlin/assertk/assertions/iterable.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/IterableTest.kt
> Fixed bug in any impl causing it to break when there were several items in the list

- assertk/src/commonMain/kotlin/assertk/assertions/collection.kt
- assertk/src/commonMain/kotlin/assertk/assertions/list.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/ListTest.kt
> Contains all in order #319

- CHANGELOG.md
- assertk/src/commonMain/kotlin/assertk/assertions/list.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/ListTest.kt
Added `startsWith` and `endsWith` for `List` assertions.
This is my first contribution, so hello everybody 👋
> Added startsWith and endsWith assertions

- CHANGELOG.md
- assertk/src/commonMain/kotlin/assertk/PlatformName.kt
- assertk/src/commonMain/kotlin/assertk/assert.kt
- assertk/src/jvmMain/kotlin/assertk/assertions/any.kt
- assertk/src/jvmTest/kotlin/test/assertk/assertions/JavaAnyTest.kt
- buildSrc/src/main/kotlin/assertk.publish.gradle.kts
removed previous error deprecations
> Made all previous deprecations errors,

- .circleci/config.yml
- buildSrc/src/main/kotlin/assertk.multiplatform.gradle.kts
- buildSrc/src/main/kotlin/assertk.publish.gradle.kts
> Revert to running two build agents

- assertk/src/commonMain/kotlin/assertk/assertions/any.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/AnyTest.kt
> Add reified overloads for `KClass`-accepting functions

- CHANGELOG.md
- README.md
- gradle/libs.versions.toml
- Bumped version
- Updated setup in README
> Prepare release 0.26

- assertk/src/nativeMain/kotlin/assertk/ThreadLocalRef.kt
- buildSrc/src/main/kotlin/assertk.multiplatform.gradle.kts
- gradle/libs.versions.toml
- kotlin-js-store/yarn.lock
Refs #479. Actual WASM support will come in a follow-up as it's a little more complicated than I hoped (due to usage of coroutines in main tests, and lack of WASM coroutines).
> Update to Kotlin 1.9

- assertk/build.gradle.kts
- assertk/src/commonTest/kotlin/test/assertk/AssertFailureTest.kt
- assertk/src/commonTest/kotlin/test/assertk/AssertLambdaTest.kt
- assertk/src/commonTest/kotlin/test/assertk/runTest.kt
- assertk/src/coroutinesTest/kotlin/test/assertk/runTest.kt
- assertk/src/wasmMain/kotlin/assertk/PlatformName.kt
- assertk/src/wasmMain/kotlin/assertk/ThreadLocalRef.kt
- assertk/src/wasmMain/kotlin/assertk/assertions/support/support.kt
- assertk/src/wasmMain/kotlin/assertk/failure.kt
- assertk/src/wasmMain/kotlin/assertk/showError.kt
- assertk/src/wasmTest/kotlin/test/assertk/exceptionName.kt
- assertk/src/wasmTest/kotlin/test/assertk/runTest.kt
- build.gradle.kts
- buildSrc/src/main/kotlin/assertk.multiplatform.gradle.kts
- gradle/libs.versions.toml
> Add support for WASM target

- assertk/src/commonMain/kotlin/assertk/assertions/array.kt
- assertk/src/commonMain/kotlin/assertk/assertions/iterable.kt
- assertk/src/commonMain/kotlin/assertk/assertions/sequence.kt
> fix incorrect usage of contains in some kdoc examples

- CHANGELOG.md
- gradle/libs.versions.toml
this is fairly arbitrary but honestly should've happened a while ago
#488
> bump version for dev, the next planned release is 1.0.0

- assertk/src/commonMain/kotlin/assertk/assertions/charsequence.kt
- assertk/src/commonTest/kotlin/test/assertk/assertions/CharSequenceTest.kt
> Add `doesNotContainMatch` assertion for CharSequence
